# Generated by Django 5.1.4 on 2026-04-21 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_alter_addproduct_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='media/category/')),
            ],
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
        migrations.AddField(
            model_name='addproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.category'),
        ),
    ]
